name: Lint, Test & Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      - name: Clean
        run: ./gradlew clean

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Assemble debug
        run: ./gradlew assembleDebug
